export enum ErrorCode {
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  NOT_FOUND = 'NOT_FOUND',
  CONFLICT = 'CONFLICT',
  INTERNAL_ERROR = 'INTERNAL_ERROR',

  USER_NOT_FOUND = 'USER_NOT_FOUND',
  EMAIL_ALREADY_REGISTERED = 'EMAIL_ALREADY_REGISTERED',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',

  VEHICLE_NOT_FOUND = 'VEHICLE_NOT_FOUND',

  DEVICE_NOT_FOUND = 'DEVICE_NOT_FOUND',
  DEVICE_IDENTIFIER_ALREADY_REGISTERED = 'DEVICE_IDENTIFIER_ALREADY_REGISTERED',
  DEVICE_INACTIVE = 'DEVICE_INACTIVE',
  INVALID_DEVICE_TOKEN = 'INVALID_DEVICE_TOKEN',

  GEOFENCE_NOT_FOUND = 'GEOFENCE_NOT_FOUND',
  TRIP_NOT_FOUND = 'TRIP_NOT_FOUND',
  ALERT_NOT_FOUND = 'ALERT_NOT_FOUND',
}
